//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteManager.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeText() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoteManager.Infrastructure.Resources.HomeText", typeof(HomeText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta activida.
        /// </summary>
        public static string AccountActivated {
            get {
                return ResourceManager.GetString("AccountActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta activida con exito.
        /// </summary>
        public static string AccountActivatedCorrectly {
            get {
                return ResourceManager.GetString("AccountActivatedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de cuenta.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepto.
        /// </summary>
        public static string Acept {
            get {
                return ResourceManager.GetString("Acept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptada.
        /// </summary>
        public static string Acepted {
            get {
                return ResourceManager.GetString("Acepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un conflicto.
        /// </summary>
        public static string AConflictOccurred {
            get {
                return ResourceManager.GetString("AConflictOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo adquisición.
        /// </summary>
        public static string AcquisitionCost {
            get {
                return ResourceManager.GetString("AcquisitionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIÓN.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIÓN REFERENCIA FAMILIAR.
        /// </summary>
        public static string AddressFamilyReference {
            get {
                return ResourceManager.GetString("AddressFamilyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUAL ES LA DIRECCÓN DE SU EMPLEO.
        /// </summary>
        public static string AddressOfYouEmployment {
            get {
                return ResourceManager.GetString("AddressOfYouEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIÓN REFERENCIA.
        /// </summary>
        public static string AddressReference {
            get {
                return ResourceManager.GetString("AddressReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo de adquisición.
        /// </summary>
        public static string AdquisitionCoste {
            get {
                return ResourceManager.GetString("AdquisitionCoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tiene dirección asignada.
        /// </summary>
        public static string AlreadyAssignedAddress {
            get {
                return ResourceManager.GetString("AlreadyAssignedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado un correo a:.
        /// </summary>
        public static string AnEmailHasBeenSentTo {
            get {
                return ResourceManager.GetString("AnEmailHasBeenSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar nuevo préstamo.
        /// </summary>
        public static string ApplyForANewLoan {
            get {
                return ResourceManager.GetString("ApplyForANewLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobar.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un comprobante.
        /// </summary>
        public static string AReceiptAlreadyExists {
            get {
                return ResourceManager.GetString("AReceiptAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de cuenta bancario.
        /// </summary>
        public static string BankAccountStatement {
            get {
                return ResourceManager.GetString("BankAccountStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existen comprobantes bancarios.
        /// </summary>
        public static string BankVouchersAlreadyExist {
            get {
                return ResourceManager.GetString("BankVouchersAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quincena.
        /// </summary>
        public static string Biweekly {
            get {
                return ResourceManager.GetString("Biweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede ser mas de 100 caracteres.
        /// </summary>
        public static string CanNotBeMoreThan100Characters {
            get {
                return ResourceManager.GetString("CanNotBeMoreThan100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede ser mas de 15 caracteres.
        /// </summary>
        public static string CanNotBeMoreThan15Characters {
            get {
                return ResourceManager.GetString("CanNotBeMoreThan15Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede ser mas de 200 caracteres.
        /// </summary>
        public static string CanNotBeMoreThan200Characteres {
            get {
                return ResourceManager.GetString("CanNotBeMoreThan200Characteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede ser mas de 30 caracteres.
        /// </summary>
        public static string CanNotBeMoreThan30Characteres {
            get {
                return ResourceManager.GetString("CanNotBeMoreThan30Characteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede ser mas de 50 caracteres.
        /// </summary>
        public static string CanNotBeMoreThan50Characters {
            get {
                return ResourceManager.GetString("CanNotBeMoreThan50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede ser mas de 20 caracteres.
        /// </summary>
        public static string CanNotBeMorThan20Characters {
            get {
                return ResourceManager.GetString("CanNotBeMorThan20Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cambia de estado.
        /// </summary>
        public static string CanNotChangeStatus {
            get {
                return ResourceManager.GetString("CanNotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma la contraseña nueva.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de finalización del contrato.
        /// </summary>
        public static string ContractEndDate {
            get {
                return ResourceManager.GetString("ContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País donde nació.
        /// </summary>
        public static string CountryOfOrigin {
            get {
                return ResourceManager.GetString("CountryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string CurrenPassword {
            get {
                return ResourceManager.GetString("CurrenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles del cliente.
        /// </summary>
        public static string CustomerDetail {
            get {
                return ResourceManager.GetString("CustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARACIÓN Y AUTORIZACIÓN.
        /// </summary>
        public static string DeclarationAndAuthorization {
            get {
                return ResourceManager.GetString("DeclarationAndAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento requerido.
        /// </summary>
        public static string Documentorequerido {
            get {
                return ResourceManager.GetString("Documentorequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DOCUMENTOS.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Depende económicamente alguien de Ud.?.
        /// </summary>
        public static string DoesSomeoneEconomicallyDependOnYou {
            get {
                return ResourceManager.GetString("DoesSomeoneEconomicallyDependOnYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Tiene cuenta de banco?.
        /// </summary>
        public static string DoYouHaveABanckAccount {
            get {
                return ResourceManager.GetString("DoYouHaveABanckAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar solicitud.
        /// </summary>
        public static string EditSolicitude {
            get {
                return ResourceManager.GetString("EditSolicitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ARCHIVOS.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMACIÓN FINANCIERA.
        /// </summary>
        public static string FinalcialInformation {
            get {
                return ResourceManager.GetString("FinalcialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Género.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATOS GENERALES.
        /// </summary>
        public static string GeneralData {
            get {
                return ResourceManager.GetString("GeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a inicio.
        /// </summary>
        public static string GoToHome {
            get {
                return ResourceManager.GetString("GoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene una de interés del .
        /// </summary>
        public static string HasInterestRate {
            get {
                return ResourceManager.GetString("HasInterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene solicitudes pendientes.
        /// </summary>
        public static string HavePendingSolicitudes {
            get {
                return ResourceManager.GetString("HavePendingSolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene creditos sin pagar.
        /// </summary>
        public static string HaveUnpaidsCredits {
            get {
                return ResourceManager.GetString("HaveUnpaidsCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de contratación.
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial.
        /// </summary>
        public static string Historical {
            get {
                return ResourceManager.GetString("Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de teléfono de su casa.
        /// </summary>
        public static string HomePhoneNumber {
            get {
                return ResourceManager.GetString("HomePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desde cuando trabaja en este lugar?.
        /// </summary>
        public static string HowLongHaveYouBeenWorkingAtYourJob {
            get {
                return ResourceManager.GetString("HowLongHaveYouBeenWorkingAtYourJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿cuántos dependientes?.
        /// </summary>
        public static string HowMany {
            get {
                return ResourceManager.GetString("HowMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuantos dependientes?.
        /// </summary>
        public static string HowManyDependents {
            get {
                return ResourceManager.GetString("HowManyDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string IdCredential {
            get {
                return ResourceManager.GetString("IdCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de identificación.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de identificación.
        /// </summary>
        public static string IDType {
            get {
                return ResourceManager.GetString("IDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si no puede acceder porque ha olvidado su contraseña, por favor ingrese su correo electrónico en el siguiente campo..
        /// </summary>
        public static string IfYouCanNotLogInBecauseYouHaveForgottenYourPassword {
            get {
                return ResourceManager.GetString("IfYouCanNotLogInBecauseYouHaveForgottenYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En proceso.
        /// </summary>
        public static string InProcess {
            get {
                return ResourceManager.GetString("InProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En revisión.
        /// </summary>
        public static string InReview {
            get {
                return ResourceManager.GetString("InReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interes.
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa de interes.
        /// </summary>
        public static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales invalidas.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha invalida.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato no válido.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llave invalida.
        /// </summary>
        public static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lapso de tiempo invalido.
        /// </summary>
        public static string InvalidLapseOfTime {
            get {
                return ResourceManager.GetString("InvalidLapseOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial invalido.
        /// </summary>
        public static string InvalidSerial {
            get {
                return ResourceManager.GetString("InvalidSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado la invitación a:.
        /// </summary>
        public static string InvitationSentTo {
            get {
                return ResourceManager.GetString("InvitationSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta validado?.
        /// </summary>
        public static string IsChecked {
            get {
                return ResourceManager.GetString("IsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Termino su registro?.
        /// </summary>
        public static string IsSurveyComplete {
            get {
                return ResourceManager.GetString("IsSurveyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPLEO.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto en el trabajo.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMACIÓN DEL PRESTAMO.
        /// </summary>
        public static string LoanInformation {
            get {
                return ResourceManager.GetString("LoanInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar como administrador.
        /// </summary>
        public static string LogInAsAdministrator {
            get {
                return ResourceManager.GetString("LogInAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje enviado.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Nombre.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo 6 caracteres.
        /// </summary>
        public static string Min6Characters {
            get {
                return ResourceManager.GetString("Min6Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de teléfono celular.
        /// </summary>
        public static string MobilePhoneNumber {
            get {
                return ResourceManager.GetString("MobilePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensual.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuál es su gasto mensual.
        /// </summary>
        public static string MonthlyExpenses {
            get {
                return ResourceManager.GetString("MonthlyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuál es su Ingreso Mensual.
        /// </summary>
        public static string MonthlyIncome {
            get {
                return ResourceManager.GetString("MonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensualidades.
        /// </summary>
        public static string MonthlyPayments {
            get {
                return ResourceManager.GetString("MonthlyPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meses.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        public static string Motive {
            get {
                return ResourceManager.GetString("Motive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deben ser 3 digitos.
        /// </summary>
        public static string MustBe3Digist {
            get {
                return ResourceManager.GetString("MustBe3Digist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deben ser 5 digitos.
        /// </summary>
        public static string MustBe5Digist {
            get {
                return ResourceManager.GetString("MustBe5Digist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deben ser 9 digitos.
        /// </summary>
        public static string MustBe9Digits {
            get {
                return ResourceManager.GetString("MustBe9Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi solicitud está.
        /// </summary>
        public static string MySolicitudeThis {
            get {
                return ResourceManager.GetString("MySolicitudeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del banco.
        /// </summary>
        public static string NameOfBanck {
            get {
                return ResourceManager.GetString("NameOfBanck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del empleador o empresa.
        /// </summary>
        public static string NameOfEmployerCompany {
            get {
                return ResourceManager.GetString("NameOfEmployerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de su Jefe.
        /// </summary>
        public static string NameOfYouSupervisor {
            get {
                return ResourceManager.GetString("NameOfYouSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo comentario.
        /// </summary>
        public static string NewComment {
            get {
                return ResourceManager.GetString("NewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo credito.
        /// </summary>
        public static string NewCredit {
            get {
                return ResourceManager.GetString("NewCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña nueva.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay información para mostrar.
        /// </summary>
        public static string NoInformationDisplay {
            get {
                return ResourceManager.GetString("NoInformationDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros para mostrar.
        /// </summary>
        public static string NoRecordsDisplay {
            get {
                return ResourceManager.GetString("NoRecordsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        public static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es un archivo valido.
        /// </summary>
        public static string NotAValidFile {
            get {
                return ResourceManager.GetString("NotAValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha sido recomendado. Su solicitud se revisará detalladamente para darle una respuesta..
        /// </summary>
        public static string NotRecommended {
            get {
                return ResourceManager.GetString("NotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opción no disponible.
        /// </summary>
        public static string OptionNotDisponable {
            get {
                return ResourceManager.GetString("OptionNotDisponable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La constraseña se ha cambiado correctamente..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas no coinciden.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia de pagos.
        /// </summary>
        public static string PaymentsFrecuency {
            get {
                return ResourceManager.GetString("PaymentsFrecuency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de teléfono.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar de expedición de ID.
        /// </summary>
        public static string PlaceOfIssueOfID {
            get {
                return ResourceManager.GetString("PlaceOfIssueOfID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione un archivo PDF o JPG.
        /// </summary>
        public static string PlaseSelectAPDFOrJPGFile {
            get {
                return ResourceManager.GetString("PlaseSelectAPDFOrJPGFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago anticipado.
        /// </summary>
        public static string Prepaid {
            get {
                return ResourceManager.GetString("Prepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobante de domicilio.
        /// </summary>
        public static string ProofOfAddress {
            get {
                return ResourceManager.GetString("ProofOfAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobante de pago.
        /// </summary>
        public static string ProofOfPayment {
            get {
                return ResourceManager.GetString("ProofOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proporcione el nombre de su recomendado.
        /// </summary>
        public static string ProvideTheNameOfYourRecommended {
            get {
                return ResourceManager.GetString("ProvideTheNameOfYourRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proporcione el correo electrónico de su recomendado.
        /// </summary>
        public static string ProvideYourRecommendedEmailAddress {
            get {
                return ResourceManager.GetString("ProvideYourRecommendedEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendar.
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendar cliente.
        /// </summary>
        public static string RecommendCustomer {
            get {
                return ResourceManager.GetString("RecommendCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recomendar amigos.
        /// </summary>
        public static string RecommendFriends {
            get {
                return ResourceManager.GetString("RecommendFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro no encontrado.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REFERENCIA.
        /// </summary>
        public static string Refence {
            get {
                return ResourceManager.GetString("Refence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La referencia no existe.
        /// </summary>
        public static string ReferenceDoesNotExist {
            get {
                return ResourceManager.GetString("ReferenceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REFERENCIA DE UN FAMILIAR QUE NO VIVA EN SU CASA.
        /// </summary>
        public static string RefereneFromAFamilyWhoDoesNotLiveAtHome {
            get {
                return ResourceManager.GetString("RefereneFromAFamilyWhoDoesNotLiveAtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe el correo registrado.
        /// </summary>
        public static string RegisteredMailAlreadyExists {
            get {
                return ResourceManager.GetString("RegisteredMailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazada.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación con el solicitante.
        /// </summary>
        public static string RelationshipWithTheApplicant {
            get {
                return ResourceManager.GetString("RelationshipWithTheApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de la solicitud.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo requerido.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado con éxito.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar contraseña.
        /// </summary>
        public static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string SingOff {
            get {
                return ResourceManager.GetString("SingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de seguridad.
        /// </summary>
        public static string SocialSecurityNumber {
            get {
                return ResourceManager.GetString("SocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string Solicitudes {
            get {
                return ResourceManager.GetString("Solicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado o departamento donde nació.
        /// </summary>
        public static string StateOfOrigin {
            get {
                return ResourceManager.GetString("StateOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # Calle, #departamento.
        /// </summary>
        public static string StreetApartament {
            get {
                return ResourceManager.GetString("StreetApartament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plazos.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo es demasiado grande.
        /// </summary>
        public static string TheFileIsTooLarge {
            get {
                return ResourceManager.GetString("TheFileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La encuesta ya esta asignada.
        /// </summary>
        public static string TheSurveyIsAlreadyAssigned {
            get {
                return ResourceManager.GetString("TheSurveyIsAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor no es cero.
        /// </summary>
        public static string TheValueIsNotZero {
            get {
                return ResourceManager.GetString("TheValueIsNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string ToReturn {
            get {
                return ResourceManager.GetString("ToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total a pagar.
        /// </summary>
        public static string TotaToPay {
            get {
                return ResourceManager.GetString("TotaToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe el nombre de usuario.
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar correo electrónico.
        /// </summary>
        public static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor no puede ser cero.
        /// </summary>
        public static string ValueCanNotBeZero {
            get {
                return ResourceManager.GetString("ValueCanNotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuál es su número de Seguro Social?.
        /// </summary>
        public static string WhatIsSocialSecurityNumber {
            get {
                return ResourceManager.GetString("WhatIsSocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuál es su compañía de celular.
        /// </summary>
        public static string WhatIsYouCellPhoneCompany {
            get {
                return ResourceManager.GetString("WhatIsYouCellPhoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuál es su apellido?.
        /// </summary>
        public static string WhatIsYouLastName {
            get {
                return ResourceManager.GetString("WhatIsYouLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuál es su nombre?.
        /// </summary>
        public static string WhatIsYourFirstName {
            get {
                return ResourceManager.GetString("WhatIsYourFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuál es su segundo nombre?.
        /// </summary>
        public static string WhatIsYourMiddleName {
            get {
                return ResourceManager.GetString("WhatIsYourMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué tipo de tareas realiza en su trabajo?.
        /// </summary>
        public static string WhatKindOfActivitiesDoYouDoInYourJob {
            get {
                return ResourceManager.GetString("WhatKindOfActivitiesDoYouDoInYourJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor hora para llamar.
        /// </summary>
        public static string WhatWouldBeTheBestTimeToCall {
            get {
                return ResourceManager.GetString("WhatWouldBeTheBestTimeToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuándo termina su contrato?.
        /// </summary>
        public static string WhenDoesYouContractEnd {
            get {
                return ResourceManager.GetString("WhenDoesYouContractEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Donde vive es?.
        /// </summary>
        public static string WhereDoYoyReside {
            get {
                return ResourceManager.GetString("WhereDoYoyReside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad que realiza en su trabajo.
        /// </summary>
        public static string WorkActivity {
            get {
                return ResourceManager.GetString("WorkActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas de trabajo por semana.
        /// </summary>
        public static string WorkingHoursPerWeek {
            get {
                return ResourceManager.GetString("WorkingHoursPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono de trabajo.
        /// </summary>
        public static string WorkPhoneNumber {
            get {
                return ResourceManager.GetString("WorkPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Años viviendo en EU.
        /// </summary>
        public static string YearsLivingInTheUSA {
            get {
                return ResourceManager.GetString("YearsLivingInTheUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SI.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes permiso.
        /// </summary>
        public static string YouDoNotHavePermission {
            get {
                return ResourceManager.GetString("YouDoNotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene permisos para cambiar la contraseña.
        /// </summary>
        public static string YouDoNotHavePermissionsToChangeThePassword {
            get {
                return ResourceManager.GetString("YouDoNotHavePermissionsToChangeThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha registrado correctamente..
        /// </summary>
        public static string YouHaveSuccessfullyRegistered {
            get {
                return ResourceManager.GetString("YouHaveSuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su primer pago sería.
        /// </summary>
        public static string YourFirstPaymentWouldBe {
            get {
                return ResourceManager.GetString("YourFirstPaymentWouldBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su tasa de interés es del .
        /// </summary>
        public static string YourInterestRateIs {
            get {
                return ResourceManager.GetString("YourInterestRateIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
